### ISSUE TITLE
Issue observed with esp32c6 dev board

### ISSUE THREAD

**Issue by Huzuri** [petrows/esp-32-tm1637#11]
Since the gpio driver is in use for the latest IDF's. The issue is observed with the initialisation of the GPIO pins for clk and data

**Comment by Huzuri** [comment]
> Since the gpio driver is in use for the latest IDF's. The issue is observed with the initialisation of the GPIO pins for clk and data

The issue can be resolved with the help gpio pins reset API beforehand they are being used

**Comment by Huzuri** [comment]
can be closed with this PR:https://github.com/petrows/esp-32-tm1637/pull/12

**Comment by petrows** [comment]
Thanks a lot for you contribute!
